### ISSUE TITLE
"No passwd entry for user 'admin'"

### ISSUE THREAD

**Issue by Nemecle** [realitygaps/drupal_ynh#1]
Quite explicit, I tried to install it on a subdomain and got this error which prevented the installation

**Comment by realitygaps** [comment]
Apologies, the drupal_ynh package was a first attempt at packaging it- it wasnt working correctly yet, im hoping to fix it up sometime and then submit it to the apps list once i find some time.

**Comment by Nemecle** [comment]
ahah, it was worth the try tho :) thanks !
