### ISSUE TITLE
error post install 

### ISSUE THREAD

**Issue by isAAAc** [realitygaps/drupal_ynh#2]
Hi 
i just installed the paquet, 
but i have a problem when i want to go on the drupal :

`The website encountered an unexpected error. Please try again later.

Symfony\Component\HttpKernel\Exception\NotFoundHttpException: in Drupal\Core\PathProcessor\PathProcessorFront->processInbound() (line 43 of core/lib/Drupal/Core/PathProcessor/PathProcessorFront.php).`

do you have an idea about this issue ?
(first time i use drupal, so i'm really lost)

thx for your help

**Comment by isAAAc** [comment]
i can touch the install page using directly without any other action since my first post :  https://mydomain.tld/drupal/core/install.php

**Comment by realitygaps** [comment]
this package was a work in progress that wasnt completed, so it probably wont work. 
I havent had a chance to fix it correctly and make it work yet. I'll update the readme to reflect this.
